/**
 * Foundry scaffolder — PURE logic for generating a plugin from templates.
 *
 * @behavior
 * Takes ScaffoldParams (name, hooks, tools) and returns a map of relative
 * path → file content. The generated plugin conforms to the six DFT axioms
 * by construction: the templates ARE the codified standard.
 *
 * @invariants
 * - scaffoldPlugin is pure: same params in → same file map out.
 * - No I/O, no filesystem — the caller (cli.ts) writes the files.
 * - Every generated file passes validatePlugin (the validator is the proof).
 * - Generated logic files have no I/O imports, no Date.now(), @dft docblocks.
 *
 * @dft
 * - Tested via tests/foundry/scaffold.spec.ts with inline params.
 * - The spec asserts the generated files PASS validatePlugin (round-trip).
 */

import type { ScaffoldParams, GeneratedFiles } from "./types.js";

// ── Template helpers ─────────────────────────────────────────────────────

/** Convert a plugin name to PascalCase for type names: "oc-my-plugin" → "OcMyPlugin". */
function toPascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Convert a plugin name to a camelCase identifier: "oc-my-plugin" → "ocMyPlugin". */
function toCamelCase(name: string): string {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/** The short name without the "oc-" prefix: "oc-session-guard" → "session-guard". */
function shortName(name: string): string {
  return name.startsWith("oc-") ? name.slice(3) : name;
}

/** The logic module name: "oc-session-guard" → "session-guard-logic". */
function logicModuleName(name: string): string {
  return `${shortName(name)}-logic`;
}

// ── Templates (the codified standard) ────────────────────────────────────

function manifestTemplate(params: ScaffoldParams): string {
  const contracts: Record<string, string[]> = {};
  if (params.tools.length > 0) contracts.tools = params.tools;
  if (params.hooks.length > 0) contracts.hooks = params.hooks;
  const manifest = {
    id: params.name,
    name: toPascalCase(params.name),
    description: params.description ?? `Plugin generated by the foundry.`,
    contracts,
    activation: { onStartup: true },
    configSchema: { type: "object", additionalProperties: false, properties: {} },
  };
  return JSON.stringify(manifest, null, 2) + "\n";
}

function packageJsonTemplate(params: ScaffoldParams): string {
  return `{
  "name": "${params.name}",
  "version": "0.1.0",
  "type": "module",
  "main": "src/index.ts",
  "dependencies": {}
}
`;
}

function logicTemplate(params: ScaffoldParams): string {
  const pascal = toPascalCase(params.name);
  const logicName = logicModuleName(params.name);

  // Generate a pure sample function + report type to seed the pattern.
  const sampleFn = params.tools.length > 0
    ? `
/**
 * Sample pure function — replace with your plugin's logic.
 * Takes immutable input, returns a NEW object + a CheckResult report.
 * Never mutates input; never calls I/O; never calls Date.now().
 */
export function process${pascal}(
  input: ${pascal}Input,
  options: { nowMs: number },
): { result: ${pascal}Result; report: ${pascal}Report } {
  const result: ${pascal}Result = { processed: true, count: input.items.length };
  const report: ${pascal}Report = {
    inputCount: input.items.length,
    outputCount: result.count,
    processedAt: options.nowMs,
  };
  return { result, report };
}`
    : "";

  const types = params.tools.length > 0
    ? `
export interface ${pascal}Input {
  items: unknown[];
}

export interface ${pascal}Result {
  processed: boolean;
  count: number;
}

export interface ${pascal}Report {
  inputCount: number;
  outputCount: number;
  processedAt: number;
}`
    : "";

  return `/**
 * ${pascal} — pure logic seam.
 *
 * @behavior
 * All decision logic for the ${params.name} plugin. Pure functions take
 * immutable input, return a NEW object + a CheckResult report, and never
 * touch the filesystem, call Date.now(), or perform I/O.
 *
 * @invariants
 * - Every function is pure: same input → same output, no side effects.
 * - No imports of I/O modules (node:fs, node:http, etc.).
 * - No Date.now() / Math.random() — time is injected via options.nowMs.
 * - Mutating functions return a report (CheckResult pattern).
 *
 * @dft
 * - Tested in ${logicName}.spec.ts with inline data, zero fixtures.
 * - No filesystem, no clock — fully deterministic.
 */

${types}
${sampleFn}
`;
}

function ioTemplate(params: ScaffoldParams): string {
  const pascal = toPascalCase(params.name);
  return `/**
 * ${pascal} — I/O Protocol wrapper.
 *
 * @behavior
 * Declares the Protocol types for I/O and provides the real filesystem
 * implementation. The plugin's index.ts accepts these as injectable
 * functions, so tests inject in-memory doubles.
 *
 * @invariants
 * - Protocol types (Reader/Writer) are declared here, not in logic files.
 * - Logic files depend only on the types, never on the implementation.
 * - The real implementation reads/writes the filesystem; tests inject doubles.
 *
 * @dft
 * - Protocol types tested via integration tests with in-memory doubles.
 * - No logic here — only I/O wiring.
 */

import { readFileSync, writeFileSync } from "node:fs";

export interface ${pascal}Reader {
  (path?: string): unknown | null;
}

export interface ${pascal}Writer {
  (data: unknown, path?: string): void;
}

export function read${pascal}(path?: string): unknown | null {
  try {
    const raw = readFileSync(path ?? "data.json", "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export function write${pascal}(data: unknown, path?: string): void {
  writeFileSync(path ?? "data.json", JSON.stringify(data, null, 2), "utf8");
}
`;
}

function indexTemplate(params: ScaffoldParams): string {
  const pascal = toPascalCase(params.name);
  const camel = toCamelCase(params.name);
  const logicName = logicModuleName(params.name);

  // Generate hook registrations.
  const hookRegistrations = params.hooks
    .map((hook) => {
      const hookName = hook.replace(/[-_]/g, " ");
      return `
    // ── Hook: ${hook} ──────────────────────────────────────────
    api.registerHook("${hook}", async (event) => {
      try {
        // TODO: read state via reader, call pure logic, write via writer.
        api.logger?.info?.("[${params.name}] ${hookName} hook fired");
      } catch (err) {
        api.logger?.error?.("[${params.name}] ${hook} failed: " + String(err));
      }
    }, { name: "${params.name}-${hook}" });`;
    })
    .join("\n");

  // Generate tool registrations.
  const toolRegistrations = params.tools
    .map((tool) => {
      return `
    // ── Tool: ${tool} ──────────────────────────────────────────
    api.registerTool({
      name: "${tool}",
      description: "${tool} tool — generated by the foundry. Replace with real behavior.",
      parameters: Type.Object({}),
      async execute(_id: string, _params: Record<string, unknown>) {
        try {
          return {
            content: [{ type: "text" as const, text: JSON.stringify({ ok: true, tool: "${tool}" }) }],
          };
        } catch (err) {
          return {
            content: [{ type: "text" as const, text: "${tool} failed: " + String(err) }],
          };
        }
      },
    });`;
    })
    .join("\n");

  const logicImport = params.tools.length > 0
    ? `import type { ${pascal}Input, ${pascal}Result, ${pascal}Report } from "./${logicName}.js";`
    : "";
  const ioImport = params.tools.length > 0
    ? `import { read${pascal}, write${pascal}, type ${pascal}Reader, type ${pascal}Writer } from "./${shortName(params.name)}-io.js";`
    : "";

  return `/**
 * ${pascal} — plugin entry point (wiring layer).
 *
 * @behavior
 * Wires hooks and tools to the pure logic seam via the I/O Protocol.
 * Delegates all decisions to ${logicName}.ts; all I/O to the Protocol wrapper.
 *
 * @invariants
 * - No logic here — only wiring (read → pure call → write).
 * - No direct node:fs imports — I/O goes through the Protocol wrapper.
 * - Hooks catch errors and log (never block agent runs).
 *
 * @dft
 * - Tested via integration tests with in-memory Protocol doubles.
 * - Pure logic tested separately in ${logicName}.spec.ts.
 */

import { definePluginEntry, Type, type PluginApi } from "../../shared/types.js";
${logicImport}
${ioImport}

export interface ${pascal}Config {
  // TODO: add config fields
}

export default definePluginEntry({
  id: "${params.name}",
  name: "${pascal}",
  description: "${params.description ?? `Plugin generated by the foundry.`}",
  register(api: PluginApi, config?: Record<string, unknown>) {
    const cfg = (config as ${pascal}Config) ?? {};
${hookRegistrations}
${toolRegistrations}
  },
});
`;
}

function manifestSpecTemplate(params: ScaffoldParams): string {
  return `/**
 * ${params.name} manifest + structure conformance test.
 *
 * @dft
 * - Structural: asserts the manifest declares what index.ts registers.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { existsSync } from "node:fs";

describe("${params.name} plugin", () => {
  const pluginDir = resolve(process.cwd(), "src/plugins/${params.name}");

  it("manifest exists", () => {
    expect(existsSync(resolve(pluginDir, "openclaw.plugin.json"))).toBe(true);
  });

  it("entry point exists", () => {
    expect(existsSync(resolve(pluginDir, "src/index.ts"))).toBe(true);
  });

  const manifest = JSON.parse(
    readFileSync(resolve(pluginDir, "openclaw.plugin.json"), "utf8")
  );

  ${params.tools.length > 0 ? `it("declares expected tools", () => {
    expect(manifest.contracts.tools).toEqual(${JSON.stringify(params.tools)});
  });` : "it('has no tools declared', () => { expect(manifest.contracts.tools ?? []).toEqual([]); })"}
});
`;
}

function unitSpecTemplate(params: ScaffoldParams): string {
  const pascal = toPascalCase(params.name);
  const logicName = logicModuleName(params.name);

  if (params.tools.length === 0) {
    return `/**
 * ${params.name} pure logic unit tests.
 *
 * @dft
 * - Pure: inline data, zero fixtures, no filesystem.
 * - Deterministic: injected nowMs, no Date.now().
 */

import { describe, it, expect } from "vitest";

describe("${logicName} pure logic", () => {
  it("placeholder — add pure logic tests", () => {
    expect(true).toBe(true);
  });
});
`;
  }

  return `/**
 * ${params.name} pure logic unit tests.
 *
 * @dft
 * - Pure: inline data, zero fixtures, no filesystem.
 * - Deterministic: injected nowMs, no Date.now().
 */

import { describe, it, expect } from "vitest";
import { process${pascal}, type ${pascal}Input } from "../src/${logicName}.js";

const NOW = 2_000_000_000;

describe("${logicName} pure logic", () => {
  it("processes input and returns a CheckResult report", () => {
    const input: ${pascal}Input = { items: [1, 2, 3] };
    const { result, report } = process${pascal}(input, { nowMs: NOW });

    expect(result.processed).toBe(true);
    expect(result.count).toBe(3);
    expect(report.inputCount).toBe(3);
    expect(report.outputCount).toBe(3);
    expect(report.processedAt).toBe(NOW);
  });

  it("is deterministic — same input → same output", () => {
    const input: ${pascal}Input = { items: ["a", "b"] };
    const a = process${pascal}(input, { nowMs: NOW });
    const b = process${pascal}(input, { nowMs: NOW });
    expect(a).toEqual(b);
  });
});
`;
}

function integrationSpecTemplate(params: ScaffoldParams): string {
  const pascal = toPascalCase(params.name);
  const logicName = logicModuleName(params.name);

  return `/**
 * ${params.name} integration test — wiring + real Protocol doubles.
 *
 * @dft
 * - Uses a REAL in-memory Protocol double (not vi.fn() patch-over).
 * - Tests the wiring (index.ts) delegates to the pure seam correctly.
 */

import { describe, it, expect, vi } from "vitest";
import plugin from "../src/index.js";

describe("${params.name} plugin wiring", () => {
  it("registers the expected hooks and tools", () => {
    const hooks: string[] = [];
    const tools: string[] = [];
    const api = {
      registerHook: (events: string | string[], _handler: unknown) => {
        if (typeof events === "string") hooks.push(events);
        else hooks.push(...events);
      },
      registerTool: (tool: { name: string }) => tools.push(tool.name),
    };

    plugin.register(api as never, {});

    ${params.hooks.length > 0 ? `expect(hooks).toEqual(${JSON.stringify(params.hooks)});` : "expect(hooks).toEqual([]);"}
    ${params.tools.length > 0 ? `expect(tools).toEqual(${JSON.stringify(params.tools)});` : "expect(tools).toEqual([]);"}
  });
});
`;
}

// ── The scaffolder (pure) ────────────────────────────────────────────────

/**
 * Generate a complete plugin file tree from params. Pure: same params in →
 * same file map out. No I/O — the caller writes the files to disk.
 *
 * Every generated plugin passes validatePlugin by construction: the templates
 * ARE the codified standard.
 */
export function scaffoldPlugin(params: ScaffoldParams): GeneratedFiles {
  const files: GeneratedFiles = new Map();

  // Root files.
  files.set("openclaw.plugin.json", manifestTemplate(params));
  files.set("package.json", packageJsonTemplate(params));

  // Source files.
  files.set(`src/${logicModuleName(params.name)}.ts`, logicTemplate(params));
  if (params.tools.length > 0) {
    files.set(`src/${shortName(params.name)}-io.ts`, ioTemplate(params));
  }
  files.set("src/index.ts", indexTemplate(params));

  // Test files.
  files.set("tests/manifest.spec.ts", manifestSpecTemplate(params));
  files.set(`tests/${logicModuleName(params.name)}.spec.ts`, unitSpecTemplate(params));
  files.set("tests/integration.spec.ts", integrationSpecTemplate(params));

  return files;
}

// Re-export helpers for unit testing.
export { toPascalCase, toCamelCase, shortName, logicModuleName };
